DROP DATABASE IF EXISTS instagram_db;
CREATE DATABASE instagram_db;

\c instagram_db;

DROP TABLE IF EXISTS users; 
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;

CREATE TABLE users(
id VARCHAR PRIMARY KEY,
email VARCHAR,
username VARCHAR,
password VARCHAR


);

CREATE TABLE posts(
id SERIAL PRIMARY KEY,
user_id VARCHAR REFERENCES users(id),
pictures VARCHAR,
content VARCHAR
);

CREATE TABLE comments(
id SERIAL PRIMARY KEY,
commenters_id VARCHAR REFERENCES users(id) ON DELETE CASCADE,
post_id INT REFERENCES posts(id) ON DELETE CASCADE,
content TEXT,
time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP

);
